### PR TITLE
Color Temp & Hue Dimmer 

### PR DESCRIPTION
**Pull request by paulsheldon**
Added Hue Dimmer Support
Added Color Temperature options
Updated image url's due to rawgit closing.

General code inspect tidy & spellcheck

### CODE REVIEW

**Comment by paulsheldon** [comment]
I'll be back just noticed a small fault

**Comment by paulsheldon** [comment]
Added Hue Dimmer Support
Added Color Temperature options
Updated image url's due to rawgit closing.

General code inspect tidy & spellcheck

**Comment by paulsheldon** [comment]
If you no longer use ST I would be happy to move this onto my repository and keep reference to you as author

**Comment by stephack** [comment]
Thanks for your contribution Paul. You are correct. I no longer use ST so you are free to use your own repo as long as you retain the contributions/credit list in the header and define where you work begins in the changelogs.

Happy Coding!
Stephan

**Pull request closed without merging**
